/**
 * Immutable, allowlisted conversation-report snapshots (design §7).
 *
 * The chat surface passes its currently visible message array into a pure
 * builder when the header action opens. The dialog receives plain immutable
 * snapshot data — never Vue refs, message-store objects, metadata objects,
 * or URLs.
 *
 * Privacy boundary (design §7.3, §18.1): the builder copies ONLY primitive
 * allowlisted values (IDs, role, content type, visible content text, safe
 * generated bytes, timestamp, model, omission boolean). It never retains
 * `ChatV2MessageView`, metadata objects, attachments, paste cache, tool data,
 * reasoning, URLs, or paths.
 */
import type { ChatV2MessageView } from "@/entityTypes/aiChatV2Types";
import { MessageType, type ChatMessage } from "@/entityTypes/commonType";
import type {
  AIContentType,
  AIConversationReportSurface,
} from "@/entityTypes/aiContentReportTypes";

export interface ConversationReportImageCandidate {
  readonly sourceId: string;
  readonly dataBase64?: string;
  readonly mimeType?: string;
}

export interface ConversationReportRelatedUser {
  readonly itemId: string;
  readonly messageId: string;
  readonly sourceIndex: number;
  readonly role: "user";
  readonly contentType: "text";
  readonly text: string;
  readonly omittedAttachmentContent: boolean;
  readonly generatedAt?: string;
}

export interface ConversationReportCandidate {
  readonly itemId: string;
  readonly messageId: string;
  readonly sourceIndex: number;
  readonly role: "assistant";
  readonly contentType: AIContentType;
  readonly text?: string;
  readonly images: readonly ConversationReportImageCandidate[];
  readonly evidenceUnavailable: boolean;
  readonly generatedAt?: string;
  readonly model?: string;
  readonly relatedUser?: ConversationReportRelatedUser;
}

export interface ConversationReportSnapshot {
  readonly snapshotId: string;
  readonly conversationId: string;
  readonly surface: AIConversationReportSurface;
  readonly createdAt: string;
  readonly candidates: readonly ConversationReportCandidate[];
}

/** True when a metadata object carries excluded content (design §7.3).
 * Checks the real ChatV2MessageMetadata fields that represent content we do
 * NOT copy into the snapshot: attachments, reasoning, tool data. */
function metadataHasExcludedContent(meta: unknown): boolean {
  if (!meta || typeof meta !== "object") return false;
  const m = meta as Record<string, unknown>;
  return Boolean(
    (Array.isArray(m.attachments) && (m.attachments as unknown[]).length > 0) ||
      m.reasoning !== undefined ||
      m.toolCallId !== undefined ||
      m.toolName !== undefined ||
      m.toolArguments !== undefined ||
      m.toolResult !== undefined
  );
}

/** Safe generated-image bytes only — never copies a URL or path (design §7.2).
 * `ChatV2GeneratedImage` is `OpenAIChatImage`, whose `b64_json`/`mime_type` are
 * already typed optional strings — so no casts are needed. */
function extractChatV2Images(
  message: ChatV2MessageView
): ConversationReportImageCandidate[] {
  const generated = message.metadata?.generatedImages ?? [];
  const out: ConversationReportImageCandidate[] = [];
  for (let i = 0; i < generated.length && out.length < 3; i++) {
    const g = generated[i];
    const b64 = g.b64_json;
    if (typeof b64 === "string" && b64.length > 0) {
      out.push({
        sourceId: `${message.id}-img-${i}`,
        dataBase64: b64,
        mimeType: g.mime_type ?? "image/png",
      });
    }
  }
  return out;
}

function deriveContentType(
  hasText: boolean,
  images: ConversationReportImageCandidate[]
): AIContentType {
  const hasImages = images.length > 0;
  if (hasImages && hasText) return "mixed";
  if (hasImages) return "image";
  return "text";
}

/**
 * Build a snapshot from Chat V2 visible messages (design §7.1, §7.2, §22.1).
 *
 * Uses a single forward pass with `lastVisibleUser` state to compute
 * related-user associations in O(n) time and O(k) memory (design §22.1):
 *   lastVisibleUser = null
 *   for each visible row in order:
 *     if row is eligible user: lastVisibleUser = sanitized snapshot
 *     if row is eligible assistant:
 *       attach lastVisibleUser
 *       lastVisibleUser = null after completing the pair
 *     if row is a completed assistant before any user: do not reuse earlier user
 */
export function buildChatV2ConversationSnapshot(input: {
  conversationId: string;
  messages: readonly ChatV2MessageView[];
  activeAssistantMessageId: string | null;
  streamStatus: "idle" | "streaming" | "cancelled" | "error";
}): ConversationReportSnapshot {
  const { conversationId, messages } = input;
  const candidates: ConversationReportCandidate[] = [];

  let lastVisibleUser: ConversationReportRelatedUser | null = null;

  for (let i = 0; i < messages.length; i++) {
    const m = messages[i];
    if (m.conversationId !== conversationId) continue;

    // Eligibility: assistant, message-type, not active streaming placeholder,
    // non-empty text or safe images.
    const isActiveStreaming =
      input.activeAssistantMessageId === m.id &&
      input.streamStatus === "streaming";
    const isAssistant = m.role === "assistant";
    const isEligibleType =
      m.messageType !== MessageType.TOOL_CALL &&
      m.messageType !== MessageType.TOOL_RESULT;
    const hasText = typeof m.content === "string" && m.content.length > 0;
    const images = extractChatV2Images(m);
    const hasEvidence = hasText || images.length > 0;

    if (m.role === "user") {
      // Track the most recent visible user message as a candidate related-user.
      lastVisibleUser = {
        itemId: `user-${m.id}`,
        messageId: m.id,
        sourceIndex: i,
        role: "user",
        contentType: "text",
        text: m.content,
        omittedAttachmentContent: metadataHasExcludedContent(m.metadata),
        generatedAt: m.timestamp,
      };
      continue;
    }

    if (!isAssistant || !isEligibleType || isActiveStreaming || !hasEvidence) {
      // Tool/permission/system/empty rows do NOT reset lastVisibleUser.
      continue;
    }

    // A new visible user replaces lastVisibleUser; a completed assistant
    // before any user means no relation (don't reuse an earlier user).
    const candidate: ConversationReportCandidate = {
      itemId: `ai-${m.id}`,
      messageId: m.id,
      sourceIndex: i,
      role: "assistant",
      contentType: deriveContentType(hasText, images),
      text: hasText ? m.content : undefined,
      images,
      evidenceUnavailable: !hasEvidence,
      generatedAt: m.timestamp,
      model: m.model,
      relatedUser: lastVisibleUser ?? undefined,
    };
    candidates.push(candidate);
    // Consume the related user after pairing.
    lastVisibleUser = null;
  }

  return freezeSnapshot({
    snapshotId: generateSnapshotId(),
    conversationId,
    surface: "chat_v2",
    createdAt: new Date().toISOString(),
    candidates,
  });
}

/**
 * Build a snapshot from legacy chat visible messages (design §7.1, §7.2 legacy).
 * Eligible: role assistant, reportable message type, non-empty visible content,
 * not the active streaming placeholder. Tool/system/permission/error excluded.
 */
export function buildLegacyConversationSnapshot(input: {
  conversationId: string;
  messages: readonly ChatMessage[];
  streamingAssistantMessageId?: string;
}): ConversationReportSnapshot {
  const { conversationId, messages } = input;
  const candidates: ConversationReportCandidate[] = [];
  let lastVisibleUser: ConversationReportRelatedUser | null = null;

  for (let i = 0; i < messages.length; i++) {
    const m = messages[i];
    if (m.conversationId && m.conversationId !== conversationId) continue;

    // ChatMessage.timestamp is a Date. The reported timestamp is its ISO form.
    const ts =
      m.timestamp instanceof Date ? m.timestamp.toISOString() : undefined;

    if (m.role === "user") {
      lastVisibleUser = {
        itemId: `user-${m.id}`,
        messageId: m.id,
        sourceIndex: i,
        role: "user",
        contentType: "text",
        text: m.content,
        omittedAttachmentContent: metadataHasExcludedContent(m.metadata),
        generatedAt: ts,
      };
      continue;
    }

    // Eligibility: assistant role, non-empty visible content, not the active
    // streaming placeholder. Tool/system rows do not produce candidates.
    const hasText = typeof m.content === "string" && m.content.length > 0;
    const isActiveStreaming = input.streamingAssistantMessageId === m.id;
    if (m.role !== "assistant" || !hasText || isActiveStreaming) continue;

    candidates.push({
      itemId: `ai-${m.id}`,
      messageId: m.id,
      sourceIndex: i,
      role: "assistant",
      contentType: "text",
      text: m.content,
      images: [],
      evidenceUnavailable: false,
      generatedAt: ts,
      relatedUser: lastVisibleUser ?? undefined,
    });
    lastVisibleUser = null;
  }

  return freezeSnapshot({
    snapshotId: generateSnapshotId(),
    conversationId,
    surface: "legacy_chat",
    createdAt: new Date().toISOString(),
    candidates,
  });
}

/**
 * Knowledge-chat message contract (design §7.1). Knowledge messages are
 * currently untyped component-local objects; this interface makes the shape
 * explicit so the adapter does not bridge with `any`.
 */
export interface KnowledgeChatMessage {
  id: string;
  type: "user" | "ai";
  content: string;
  timestamp: Date | string;
}

/**
 * Build a snapshot from knowledge-chat visible messages (design §7.1, §7.2,
 * §11.3). Eligible: type "ai" with non-empty visible content. Knowledge
 * sources are NOT evidence and are never copied into the snapshot.
 */
export function buildKnowledgeConversationSnapshot(input: {
  conversationId: string;
  messages: readonly KnowledgeChatMessage[];
}): ConversationReportSnapshot {
  const { conversationId, messages } = input;
  const candidates: ConversationReportCandidate[] = [];
  let lastVisibleUser: ConversationReportRelatedUser | null = null;

  for (let i = 0; i < messages.length; i++) {
    const m = messages[i];
    const ts =
      m.timestamp instanceof Date ? m.timestamp.toISOString() : m.timestamp;

    if (m.type === "user") {
      lastVisibleUser = {
        itemId: `user-${m.id}`,
        messageId: m.id,
        sourceIndex: i,
        role: "user",
        contentType: "text",
        text: m.content,
        omittedAttachmentContent: false,
        generatedAt: ts,
      };
      continue;
    }

    const hasText = typeof m.content === "string" && m.content.length > 0;
    if (m.type !== "ai" || !hasText) continue;

    candidates.push({
      itemId: `ai-${m.id}`,
      messageId: m.id,
      sourceIndex: i,
      role: "assistant",
      contentType: "text",
      text: m.content,
      images: [],
      evidenceUnavailable: false,
      generatedAt: ts,
      relatedUser: lastVisibleUser ?? undefined,
    });
    lastVisibleUser = null;
  }

  return freezeSnapshot({
    snapshotId: generateSnapshotId(),
    conversationId,
    surface: "knowledge_chat",
    createdAt: new Date().toISOString(),
    candidates,
  });
}

function generateSnapshotId(): string {
  if (
    typeof crypto !== "undefined" &&
    typeof crypto.randomUUID === "function"
  ) {
    return crypto.randomUUID();
  }
  return `snap-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

/** Freeze the top-level snapshot (and arrays) in development builds (design §7.4). */
function freezeSnapshot(
  snap: ConversationReportSnapshot
): ConversationReportSnapshot {
  if (process.env.NODE_ENV !== "production") {
    return Object.freeze({
      ...snap,
      candidates: Object.freeze([...snap.candidates]),
    }) as ConversationReportSnapshot;
  }
  return snap;
}
