<template>
  <section class="ai-artifact-workspace">
    <header class="ai-artifact-workspace__header">
      <div class="ai-artifact-workspace__title" :title="artifact.title">
        <v-icon size="small" class="mr-1">mdi-file-code-outline</v-icon>
        <span class="ai-artifact-workspace__title-text">{{ artifact.title }}</span>
        <v-chip
          v-if="artifact.version > 1"
          size="x-small"
          variant="tonal"
          class="ml-2"
        >
          {{
            t("aiArtifacts.version_label", { version: artifact.version }) ||
            `Version ${artifact.version}`
          }}
        </v-chip>
      </div>
      <div class="ai-artifact-workspace__actions">
        <span class="ai-artifact-workspace__badge">
          {{ t("aiArtifacts.generated_by_ai") || "Generated by AI" }}
        </span>
        <AIContentReportButton
          :descriptor="reportDescriptor"
          :reported="reportSubmitted"
          @report="reportDialogOpen = true"
        />
        <AIContentReportDialog
          v-model="reportDialogOpen"
          :descriptor="reportDescriptor"
          :privacy-policy-url="AIFETCHLY_PRIVACY_POLICY_URL"
          @submitted="reportSubmitted = true"
        />
        <v-btn
          icon="mdi-content-copy"
          variant="text"
          size="small"
          :disabled="loading"
          :aria-label="t('aiArtifacts.copy_html') || 'Copy HTML'"
          :title="t('aiArtifacts.copy_html') || 'Copy HTML'"
          @click="emit('copy-html')"
        />
        <v-btn
          icon="mdi-close"
          variant="text"
          size="small"
          :aria-label="t('aiArtifacts.close') || 'Close artifact'"
          :title="t('aiArtifacts.close') || 'Close artifact'"
          @click="emit('close')"
        />
      </div>
    </header>
    <v-progress-linear
      v-if="loading"
      indeterminate
      height="3"
      class="ai-artifact-workspace__progress"
    />
    <div v-if="error" class="ai-artifact-workspace__error">
      <v-icon color="error" class="mr-2">mdi-alert-circle</v-icon>
      <span>{{ error }}</span>
    </div>
    <!--
      Security: artifact HTML renders ONLY in this sandboxed iframe.
      sandbox="" disables scripts, forms, popups, same-origin, and top
      navigation. NEVER add allow-same-origin, NEVER use v-html for content.
      referrerpolicy=no-referrer blocks referrer leakage.
    -->
    <iframe
      class="ai-artifact-workspace__frame"
      sandbox=""
      referrerpolicy="no-referrer"
      :srcdoc="artifact.content"
    />
  </section>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import { useI18n } from "vue-i18n";
import type { AIArtifactRecord } from "@/entityTypes/aiArtifactTypes";
import AIContentReportButton from "@/views/components/aiContentReport/AIContentReportButton.vue";
import AIContentReportDialog from "@/views/components/aiContentReport/AIContentReportDialog.vue";
import { buildArtifactDescriptor } from "@/views/components/aiContentReport/reportableOutput";
import { AIFETCHLY_PRIVACY_POLICY_URL } from "@/config/appInfo";

const props = defineProps<{
  artifact: AIArtifactRecord;
  loading?: boolean;
  error?: string;
}>();

const emit = defineEmits<{
  (e: "close"): void;
  (e: "copy-html"): void;
}>();

const { t } = useI18n();

const reportDialogOpen = ref(false);
const reportSubmitted = ref(false);
const reportDescriptor = computed(() =>
  buildArtifactDescriptor(props.artifact)
);
</script>

<style scoped>
.ai-artifact-workspace {
  display: flex;
  flex-direction: column;
  height: 100%;
  width: 100%;
  background: rgb(var(--v-theme-background));
}
.ai-artifact-workspace__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  padding: 8px 12px;
  border-bottom: 1px solid rgba(var(--v-theme-on-surface), 0.12);
  background: rgb(var(--v-theme-surface));
  flex: 0 0 auto;
}
.ai-artifact-workspace__title {
  display: flex;
  align-items: center;
  min-width: 0;
  font-weight: 600;
}
.ai-artifact-workspace__title-text {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  max-width: 50vw;
}
.ai-artifact-workspace__actions {
  display: flex;
  align-items: center;
  gap: 4px;
  flex: 0 0 auto;
}
.ai-artifact-workspace__badge {
  font-size: 11px;
  opacity: 0.65;
  margin-right: 4px;
  white-space: nowrap;
}
.ai-artifact-workspace__progress {
  flex: 0 0 auto;
}
.ai-artifact-workspace__error {
  display: flex;
  align-items: center;
  padding: 10px 14px;
  color: rgb(var(--v-theme-error));
  flex: 0 0 auto;
}
.ai-artifact-workspace__frame {
  flex: 1 1 auto;
  width: 100%;
  border: none;
  background: #fff;
}
</style>
