<template>
  <div class="ai-artifact-card" :class="{ 'ai-artifact-card--disabled': disabled }">
    <div class="ai-artifact-card__icon">
      <v-icon color="primary">mdi-file-code-outline</v-icon>
    </div>
    <div class="ai-artifact-card__body">
      <div class="ai-artifact-card__title" :title="artifact.title">
        {{ artifact.title }}
      </div>
      <div class="ai-artifact-card__meta">
        <span class="ai-artifact-card__type">
          {{ t("aiArtifacts.html_artifact") || "HTML artifact" }}
        </span>
        <span
          v-if="typeof artifact.version === 'number' && artifact.version > 1"
          class="ai-artifact-card__version"
        >
          {{
            t("aiArtifacts.version_label", { version: artifact.version }) ||
            `Version ${artifact.version}`
          }}
        </span>
        <span class="ai-artifact-card__generated">
          {{ t("aiArtifacts.generated_by_ai") || "Generated by AI" }}
        </span>
      </div>
      <div v-if="artifact.description" class="ai-artifact-card__desc">
        {{ artifact.description }}
      </div>
    </div>
    <div class="ai-artifact-card__actions">
      <v-btn
        size="small"
        variant="tonal"
        color="primary"
        :disabled="disabled"
        :title="t('aiArtifacts.open') || 'Open artifact'"
        @click="emit('open', artifact.id)"
      >
        <v-icon size="small" start>mdi-open-in-new</v-icon>
        {{ t("aiArtifacts.open") || "Open" }}
      </v-btn>
      <v-btn
        icon="mdi-content-copy"
        variant="text"
        size="small"
        :disabled="disabled"
        :title="t('aiArtifacts.copy_html') || 'Copy HTML'"
        @click="emit('copy-html', artifact.id)"
      />
      <AIContentReportButton
        :descriptor="reportDescriptor"
        :reported="reportSubmitted"
        @report="reportDialogOpen = true"
      />
      <AIContentReportDialog
        v-model="reportDialogOpen"
        :descriptor="reportDescriptor"
        @submitted="reportSubmitted = true"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import { useI18n } from "vue-i18n";
import type { AIArtifactToolMetadata } from "@/entityTypes/aiArtifactTypes";
import AIContentReportButton from "@/views/components/aiContentReport/AIContentReportButton.vue";
import AIContentReportDialog from "@/views/components/aiContentReport/AIContentReportDialog.vue";
import { buildArtifactDescriptor } from "@/views/components/aiContentReport/reportableOutput";

const props = defineProps<{
  artifact: AIArtifactToolMetadata;
  disabled?: boolean;
}>();

const emit = defineEmits<{
  (e: "open", artifactId: string): void;
  (e: "copy-html", artifactId: string): void;
}>();

const { t } = useI18n();

const reportDialogOpen = ref(false);
const reportSubmitted = ref(false);
const reportDescriptor = computed(() =>
  buildArtifactDescriptor(props.artifact)
);
</script>

<style scoped>
.ai-artifact-card {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  padding: 10px 12px;
  margin: 6px 0;
  border: 1px solid rgba(var(--v-theme-primary), 0.35);
  border-radius: 10px;
  background: rgba(var(--v-theme-primary), 0.06);
}
.ai-artifact-card--disabled {
  opacity: 0.6;
}
.ai-artifact-card__icon {
  flex: 0 0 auto;
  padding-top: 2px;
}
.ai-artifact-card__body {
  flex: 1 1 auto;
  min-width: 0;
}
.ai-artifact-card__title {
  font-weight: 600;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.ai-artifact-card__meta {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  font-size: 11px;
  opacity: 0.7;
  margin-top: 2px;
}
.ai-artifact-card__desc {
  font-size: 12px;
  opacity: 0.8;
  margin-top: 4px;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.ai-artifact-card__actions {
  display: flex;
  align-items: center;
  gap: 4px;
  flex: 0 0 auto;
}
</style>
