"use strict";

/**
 * Embedding provider kinds supported by the RAG pipeline.
 *
 * - `remote-api`: embeddings generated by the remote AI server.
 * - `local-xenova`: embeddings generated on-device via `@xenova/transformers`.
 */
export type EmbeddingProviderKind = "remote-api" | "local-xenova";

/**
 * Normalized embedding model descriptor used by the catalog, IPC layer, and UI.
 *
 * `name` is the stable, machine-readable model ID used for provider routing,
 * vector index naming, and persisted document metadata. `displayName` is the
 * UI label only and must never be used for routing decisions.
 */
export interface EmbeddingModelInfo {
  /** Stable, machine-readable model ID (e.g. "local-xenova:Xenova/all-MiniLM-L6-v2"). */
  name: string;
  /** UI label (e.g. "Xenova/all-MiniLM-L6-v2 (free)"). Presentation only. */
  displayName: string;
  /** Human-readable description. */
  description: string;
  /** Vector dimensions produced by this model. */
  dimensions: number;
  /** Provider responsible for generating embeddings for this model. */
  provider: EmbeddingProviderKind;
  /** Whether the model is free to use (drives the UI free badge). */
  is_free: boolean;
  /** Whether the model is currently available in the runtime. */
  available: boolean;
  /** For local models, the underlying library model identifier. */
  underlyingModel?: string;
}

/**
 * Result of embedding a single text via an embedding provider.
 */
export interface EmbeddingResult {
  text: string;
  embedding: number[];
  dimensions: number;
  model: string;
  provider: EmbeddingProviderKind;
}

/**
 * Result of embedding a batch of texts via an embedding provider.
 */
export interface EmbeddingBatchResult {
  embeddings: EmbeddingResult[];
  model: string;
  provider: EmbeddingProviderKind;
  dimensions: number;
}
