CREATE TABLE IF NOT EXISTS email_reply_audit_log(
id INTEGER PRIMARY KEY AUTOINCREMENT,
emailServiceId INTEGER NOT NULL,
messageId INTEGER,
draftId INTEGER,
action VARCHAR(50) NOT NULL,
actor VARCHAR(20) DEFAULT 'system',
reason TEXT,
metadataJson TEXT,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
)
