CREATE TABLE IF NOT EXISTS email_auto_reply_audit_log(
id INTEGER PRIMARY KEY AUTOINCREMENT,
emailServiceId INTEGER NOT NULL,
messageId INTEGER NOT NULL,
draftId INTEGER,
ruleId INTEGER,
action VARCHAR(50) NOT NULL,
decisionStatus VARCHAR(50) NOT NULL,
classification VARCHAR(50),
confidence REAL,
reason TEXT,
knowledgeQuery TEXT,
knowledgeSourcesJson TEXT,
generatedSubject VARCHAR(998),
generatedBodyPreview TEXT,
sentSubject VARCHAR(998),
sentBodyPreview TEXT,
requiresUserApproval INTEGER DEFAULT 1,
approvedByUser INTEGER DEFAULT 0,
errorMessage TEXT,
metadataJson TEXT,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
)
