CREATE TABLE IF NOT EXISTS email_received_message(
id INTEGER PRIMARY KEY AUTOINCREMENT,
emailServiceId INTEGER NOT NULL,
providerUid VARCHAR(255) NOT NULL,
messageId VARCHAR(998),
threadKey VARCHAR(998),
inReplyTo VARCHAR(998),
referencesHeader TEXT,
fromAddress VARCHAR(320) NOT NULL,
fromName VARCHAR(255),
replyToAddress VARCHAR(320),
toAddressesJson TEXT NOT NULL,
ccAddressesJson TEXT,
subject VARCHAR(998) NOT NULL,
bodyText TEXT,
bodyHtmlSanitized TEXT,
snippet TEXT,
receivedAt DATETIME NOT NULL,
isUnread INTEGER DEFAULT 1,
classification VARCHAR(50),
classificationConfidence REAL,
replyStatus VARCHAR(50) DEFAULT 'not_started',
processedAt DATETIME,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
)
