CREATE TABLE IF NOT EXISTS yellow_pages_platform(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL UNIQUE,
display_name TEXT NOT NULL,
base_url TEXT NOT NULL,
country TEXT NOT NULL,
language TEXT NOT NULL,
is_active BOOLEAN NOT NULL DEFAULT 1,
version TEXT NOT NULL DEFAULT '1.0.0',
rate_limit INTEGER NOT NULL DEFAULT 100,
delay_between_requests INTEGER NOT NULL DEFAULT 2000,
max_concurrent_requests INTEGER NOT NULL DEFAULT 1,
selectors TEXT NULL,
custom_extractors TEXT NULL,
type TEXT NOT NULL DEFAULT 'configuration',
class_name TEXT NULL,
module_path TEXT NULL,
settings TEXT NULL,
metadata TEXT NULL,
description TEXT NULL,
maintainer TEXT NULL,
documentation TEXT NULL,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
) 