import { contextBridge, ipcRenderer } from 'electron'
import {EXTRAMODULECHANNE_LIST,EXTRAMODULECHANNE_INSTALL,EXTRAMODULECHANNE_UNINSTALL,EXTRAMODULECHANNE_MESSAGE,OPENDIRECTORY,SYSTEM_MESSAGE,VIDEODOWNLOAD_MESSAGE,VIDEODOWNLOAD,VIDEODOWNLOAD_TASK_LIST,SEARCHSCRAPERAPI,LISTSESARCHRESUT,SEARCHEVENT,TASKSEARCHRESULTLIST,SAVESEARCHERRORLOG
  ,CHECKALLPROXY,CHECKALLPROXYMESSAGE,REMOVEFAILUREPROXY_MESSAGE,REMOVEFAILUREPROXY,  EMAILEXTRACTIONAPI,EMAILEXTRACTIONMESSAGE,
  LISTEMAILSEARCHTASK,EMAILSEARCHTASKRESULT,EMAILEXTRACTION_RESULT_EXPORT,EMAILMARKETINGTEMPLIST,EMAILMARKETINGTEMPREMOVE,EMAILMARKETINGTEMPDETAIL,EMAILMARKETINGTEMPUPDATE,EMAILMARKETINGFILTERLIST,EMAILMARKETFILTERDETAIL,EMAILMARKETFILTERUPDATE,EMAILSERVICEUPDATE,EMAILSERVICEDETAIL,EMAILSERVICELIST,EMAILSERVICEDELETE
  ,EMAILFILTERDELETE,BUCKEMAILSEND,BUCKEMAILSENDMESSAGE,SENDTESTEMAIL,RECEIVESENDTESTEMAILMESSAGE,BUCKEMAILTASKLIST,BUCKEMAILTASKSENDLOG,SOCIALACCOUNTlIST,SOCIALACCOUNTSAVE,SOCIAL_ACCOUNT_LOGIN_MESSSAGE,SOCIAL_ACCOUNT_LOGIN_UPLOADCOOKIES,SOCIAL_ACCOUNT_CLEAN_COOKIES,SOCIAL_ACCOUNT_SHOW_PLATFORMPAGE,
  VIDEODOWNLOAD_LIST,VIDEODOWNLOADTASK_RETRY,VIDEODOWNLOADITEM_RETRY,VIDEODOWNLOAD_ITEM_MESSAGE,VIDEODOWNLOADITEM_EXPLORER,VIDEODOWNLOADITEM_DELETE,VIDEODOWN_TASK_ERROR_LOG_QUERY,VIDEO_CAPTION_GENERATE,VIDEO_CAPTION_GENERATE_MESSAGE,EXTRAMODULE_UPGRADE,EXTRAMODULE_UPGRAD_MESSAGE,VIDEOTASKDOWNLOAD_RETRY_MESSAGE,VIDEODOWNLOAD_LOG_QUERY,VIDEODOWNLOAD_DETAIL_QUERY,VIDEODOWNLOAD_OPEN_CAPTIONFILE,
  SYSTEM_SETTING_LIST,SYSTEM_SETTING_UPDATE,VIDEO_INFORMATION_TRANSLATE,QUERY_USER_INFO,OPENLOGINPAGE,NATIVATECOMMAND,VIDEO_PUBLISH,EMAILSEARCHTASK_ERROR_LOG_DOWNLOAD,RETRYSEARCHTASK,CHOOSEFILEDIALOG,VIDEO_PUBLISH_RECORD_LIST,VIDEO_PUBLISH_RECORD_DELETE,VIDEO_PUBLISH_RECORD_MESSAGE,PROXYLIST,PROXYDETAIL,PROXYSAVE,PROXYCHECK,PROXYIMPORT,PROXYDELETE,
  // Schedule Management Channels
  SCHEDULE_CREATE,SCHEDULE_UPDATE,SCHEDULE_DELETE,SCHEDULE_ENABLE,SCHEDULE_DISABLE,SCHEDULE_PAUSE,SCHEDULE_RESUME,SCHEDULE_RUN_NOW,SCHEDULE_LIST,SCHEDULE_DETAIL,SCHEDULE_BY_TASK_TYPE,SCHEDULE_SEARCH,SCHEDULE_EXPORT,SCHEDULE_IMPORT,
  // Execution Management Channels
  EXECUTION_HISTORY,EXECUTION_STATISTICS,EXECUTION_RECENT,
  // Dependency Management Channels
  DEPENDENCY_ADD,DEPENDENCY_REMOVE,DEPENDENCY_GRAPH,DEPENDENCY_VALIDATE,
  // Scheduler Management Channels
  SCHEDULER_STATUS,SCHEDULER_START,SCHEDULER_STOP,SCHEDULER_RELOAD,
  // Utility Channels
  CRON_VALIDATE,CRON_NEXT_RUN_TIME,GET_LOGIN_URL,USER_CHECK_LOGIN,USER_SIGNOUT,GET_APP_INFO,GETEMAILSEARCHTASK,GET_SEARCH_TASK_DETAILS,UPDATE_SEARCH_TASK,CREATE_SEARCH_TASK_ONLY,EXPORT_SEARCH_RESULTS,KILL_SEARCH_PROCESS,
  // Yellow Pages Management Channels
  YELLOW_PAGES_PLATFORMS,YELLOW_PAGES_LIST,YELLOW_PAGES_DETAIL,YELLOW_PAGES_CREATE,YELLOW_PAGES_UPDATE,YELLOW_PAGES_DELETE,YELLOW_PAGES_START,YELLOW_PAGES_STOP,YELLOW_PAGES_PAUSE,YELLOW_PAGES_RESUME,YELLOW_PAGES_PROGRESS,YELLOW_PAGES_RESULTS,YELLOW_PAGES_EXPORT,YELLOW_PAGES_BULK,YELLOW_PAGES_HEALTH,YELLOW_PAGES_STATISTICS,YELLOW_PAGES_KILL_PROCESS,YELLOW_PAGES_CHECK_ORPHANED_PROCESSES,
  // Language Preference Channels
  LANGUAGE_PREFERENCE_GET,LANGUAGE_PREFERENCE_UPDATE,
  // RAG Management Channels
  RAG_INITIALIZE,RAG_QUERY,RAG_UPLOAD_DOCUMENT,RAG_GET_STATS,RAG_TEST_PIPELINE,RAG_GET_DOCUMENTS,RAG_GET_DOCUMENT,RAG_UPDATE_DOCUMENT,RAG_DELETE_DOCUMENT,RAG_GET_DOCUMENT_STATS,RAG_SEARCH,RAG_GET_SUGGESTIONS,RAG_GET_SEARCH_ANALYTICS,RAG_UPDATE_EMBEDDING_MODEL,RAG_GET_AVAILABLE_MODELS,RAG_TEST_EMBEDDING_SERVICE,RAG_CLEAR_CACHE,RAG_CLEANUP,RAG_CHUNK_AND_EMBED_DOCUMENT,RAG_DOWNLOAD_DOCUMENT,RAG_GET_DOCUMENT_ERROR_LOG,
  // File Dialog Channels
  SHOW_OPEN_DIALOG,GET_FILE_STATS,SAVE_TEMP_FILE,SAVE_TEMP_FILE_PROGRESS,SAVE_TEMP_FILE_COMPLETE,
  // AI Chat Channels
  AI_CHAT_MESSAGE,AI_CHAT_STREAM,AI_CHAT_STREAM_CHUNK,AI_CHAT_STREAM_COMPLETE,AI_CHAT_HISTORY,AI_CHAT_CLEAR,AI_CHAT_CONVERSATIONS,AI_KEYWORDS_GENERATE,
  // Dashboard Channels
  DASHBOARD_SUMMARY,DASHBOARD_TRENDS,DASHBOARD_SEARCH_ENGINES,DASHBOARD_EMAIL_STATUS,
  // MCP Tool Management Channels
  MCP_TOOL_LIST,MCP_TOOL_ADD,MCP_TOOL_UPDATE,MCP_TOOL_DELETE,MCP_TOOL_DISCOVER,MCP_TOOL_TOGGLE_SERVER,MCP_TOOL_TOGGLE_TOOL,MCP_TOOL_TEST_CONNECTION} from "@/config/channellist";

// window.ipcRenderer = ipcRenderer
// console.log('preload.js')
// contextBridge.exposeInMainWorld('electronAPI', {
//     userLogin: (data) => ipcRenderer.invoke('user:login', data)
// })
contextBridge.exposeInMainWorld('api', {
    send: (channel, data) => {
      // whitelist channels
      const validChannels = ['user:Login','socialtask:start','socialtask:log','socialaccount:login',EXTRAMODULECHANNE_INSTALL,EXTRAMODULECHANNE_MESSAGE,EXTRAMODULECHANNE_UNINSTALL,VIDEODOWNLOAD_MESSAGE,
        VIDEODOWNLOAD,SEARCHSCRAPERAPI,CHECKALLPROXY,REMOVEFAILUREPROXY,EMAILEXTRACTIONAPI,BUCKEMAILSEND,BUCKEMAILSENDMESSAGE,SENDTESTEMAIL,SOCIAL_ACCOUNT_LOGIN_UPLOADCOOKIES,SOCIAL_ACCOUNT_CLEAN_COOKIES,SOCIAL_ACCOUNT_SHOW_PLATFORMPAGE,VIDEODOWNLOADTASK_RETRY,VIDEODOWNLOADITEM_RETRY,VIDEODOWNLOADITEM_EXPLORER,VIDEODOWNLOADITEM_DELETE,VIDEO_CAPTION_GENERATE,EXTRAMODULE_UPGRADE,VIDEODOWNLOAD_OPEN_CAPTIONFILE,VIDEO_INFORMATION_TRANSLATE,OPENLOGINPAGE,VIDEO_PUBLISH,RETRYSEARCHTASK,VIDEO_PUBLISH_RECORD_DELETE,SAVE_TEMP_FILE,AI_CHAT_STREAM]
      console.log('send',channel,data)
      if (validChannels.includes(channel)) {
        console.log('send2',channel,data)
        ipcRenderer.send(channel, data)
      }
    },
    sendBinary: (channel, data) => {
      // whitelist channels for binary data
      const validChannels = [SAVE_TEMP_FILE]
      console.log('sendBinary',channel,data)
      if (validChannels.includes(channel)) {
        console.log('sendBinary2',channel,data)
        ipcRenderer.send(channel, data)
      }
    },
    receive: (channel, func) => {
      const validChannels = ['user:Login','socialtask:start','socialtask:log',EXTRAMODULECHANNE_INSTALL,EXTRAMODULECHANNE_MESSAGE,EXTRAMODULECHANNE_UNINSTALL,SYSTEM_MESSAGE,VIDEODOWNLOAD_MESSAGE,VIDEODOWNLOAD,
        SEARCHSCRAPERAPI,SEARCHEVENT,CHECKALLPROXYMESSAGE,REMOVEFAILUREPROXY_MESSAGE,EMAILEXTRACTIONMESSAGE,BUCKEMAILSENDMESSAGE,RECEIVESENDTESTEMAILMESSAGE,SOCIAL_ACCOUNT_LOGIN_MESSSAGE,SOCIAL_ACCOUNT_CLEAN_COOKIES,VIDEODOWNLOAD_ITEM_MESSAGE,VIDEO_CAPTION_GENERATE_MESSAGE,EXTRAMODULE_UPGRAD_MESSAGE,VIDEOTASKDOWNLOAD_RETRY_MESSAGE,VIDEO_INFORMATION_TRANSLATE,NATIVATECOMMAND,VIDEO_PUBLISH_RECORD_MESSAGE,SAVE_TEMP_FILE_PROGRESS,SAVE_TEMP_FILE_COMPLETE,AI_CHAT_STREAM_CHUNK,AI_CHAT_STREAM_COMPLETE]
      const regex="/^socialtask:log:/"

      if (validChannels.includes(channel)||channel.test(regex)) {
        // Deliberately strip event as it includes `sender`
        ipcRenderer.on(channel, (event, ...args) => func(...args))
      }
    },
    invoke: (channel, data) => {
      // whitelist channels
      const validChannels = ['user:Login',USER_CHECK_LOGIN,USER_SIGNOUT,'campaign:list','socialtask:list','socialtask:info','socialtasktype:list','tag:list','socialtask:save','socialtask:start','socialtaskrun:list','socialtaskresult:list',SOCIALACCOUNTlIST,SOCIALACCOUNTSAVE,'socialplatform:list','socialaccount:detail','socialaccount:delete',PROXYLIST,PROXYDELETE,PROXYSAVE,PROXYDETAIL,PROXYCHECK,PROXYIMPORT,EXTRAMODULECHANNE_LIST,OPENDIRECTORY,VIDEODOWNLOAD,VIDEODOWNLOAD_TASK_LIST,LISTSESARCHRESUT,SEARCHSCRAPERAPI,TASKSEARCHRESULTLIST,
        "task:create","task:update","task:delete","task:list","task:detail","task:run","task:cancel","task:results","platform:list",
        SAVESEARCHERRORLOG,LISTEMAILSEARCHTASK,EMAILSEARCHTASKRESULT,EMAILEXTRACTION_RESULT_EXPORT,EMAILMARKETINGTEMPLIST,EMAILMARKETINGTEMPREMOVE,EMAILMARKETINGTEMPDETAIL,
        EMAILMARKETINGTEMPUPDATE,EMAILMARKETINGFILTERLIST,EMAILMARKETFILTERDETAIL,EMAILMARKETFILTERUPDATE,EMAILSERVICEUPDATE,EMAILSERVICEDETAIL,EMAILSERVICELIST,EMAILSERVICEDELETE,EMAILFILTERDELETE,BUCKEMAILTASKLIST,BUCKEMAILTASKSENDLOG,VIDEODOWNLOAD_LIST,VIDEODOWN_TASK_ERROR_LOG_QUERY,VIDEODOWNLOAD_LOG_QUERY,VIDEODOWNLOAD_DETAIL_QUERY,SYSTEM_SETTING_LIST,SYSTEM_SETTING_UPDATE,QUERY_USER_INFO,EMAILSEARCHTASK_ERROR_LOG_DOWNLOAD,RETRYSEARCHTASK,CHOOSEFILEDIALOG,VIDEO_PUBLISH_RECORD_LIST,
        // Schedule Management Channels
        SCHEDULE_CREATE,SCHEDULE_UPDATE,SCHEDULE_DELETE,SCHEDULE_ENABLE,SCHEDULE_DISABLE,SCHEDULE_PAUSE,SCHEDULE_RESUME,SCHEDULE_RUN_NOW,SCHEDULE_LIST,SCHEDULE_DETAIL,SCHEDULE_BY_TASK_TYPE,SCHEDULE_SEARCH,SCHEDULE_EXPORT,SCHEDULE_IMPORT,
        // Execution Management Channels
        EXECUTION_HISTORY,EXECUTION_STATISTICS,EXECUTION_RECENT,
        // Dependency Management Channels
        DEPENDENCY_ADD,DEPENDENCY_REMOVE,DEPENDENCY_GRAPH,DEPENDENCY_VALIDATE,
        // Scheduler Management Channels
        SCHEDULER_STATUS,SCHEDULER_START,SCHEDULER_STOP,SCHEDULER_RELOAD,
        // Utility Channels
        CRON_VALIDATE,CRON_NEXT_RUN_TIME,GET_LOGIN_URL,GET_APP_INFO,GETEMAILSEARCHTASK,GET_SEARCH_TASK_DETAILS,UPDATE_SEARCH_TASK,CREATE_SEARCH_TASK_ONLY,EXPORT_SEARCH_RESULTS,KILL_SEARCH_PROCESS,
        // Yellow Pages Management Channels
        YELLOW_PAGES_PLATFORMS,YELLOW_PAGES_LIST,YELLOW_PAGES_DETAIL,YELLOW_PAGES_CREATE,YELLOW_PAGES_UPDATE,YELLOW_PAGES_DELETE,YELLOW_PAGES_START,YELLOW_PAGES_STOP,YELLOW_PAGES_PAUSE,YELLOW_PAGES_RESUME,YELLOW_PAGES_PROGRESS,YELLOW_PAGES_RESULTS,YELLOW_PAGES_EXPORT,YELLOW_PAGES_BULK,YELLOW_PAGES_HEALTH,YELLOW_PAGES_STATISTICS,YELLOW_PAGES_KILL_PROCESS,YELLOW_PAGES_CHECK_ORPHANED_PROCESSES,'yellow_pages:get_process_status',
        // Language Preference Channels
        LANGUAGE_PREFERENCE_GET,LANGUAGE_PREFERENCE_UPDATE,
        // RAG Management Channels
        RAG_INITIALIZE,RAG_QUERY,RAG_UPLOAD_DOCUMENT,RAG_GET_STATS,RAG_TEST_PIPELINE,RAG_GET_DOCUMENTS,RAG_GET_DOCUMENT,RAG_UPDATE_DOCUMENT,RAG_DELETE_DOCUMENT,RAG_GET_DOCUMENT_STATS,RAG_SEARCH,RAG_GET_SUGGESTIONS,RAG_GET_SEARCH_ANALYTICS,RAG_UPDATE_EMBEDDING_MODEL,RAG_GET_AVAILABLE_MODELS,RAG_TEST_EMBEDDING_SERVICE,RAG_CLEAR_CACHE,RAG_CLEANUP,RAG_CHUNK_AND_EMBED_DOCUMENT,RAG_DOWNLOAD_DOCUMENT,RAG_GET_DOCUMENT_ERROR_LOG,
        // File Dialog Channels
        SHOW_OPEN_DIALOG,GET_FILE_STATS,SAVE_TEMP_FILE,
        // AI Chat Channels
        AI_CHAT_MESSAGE,AI_CHAT_HISTORY,AI_CHAT_CLEAR,AI_CHAT_CONVERSATIONS,AI_KEYWORDS_GENERATE,
        // Dashboard Channels
        DASHBOARD_SUMMARY,DASHBOARD_TRENDS,DASHBOARD_SEARCH_ENGINES,DASHBOARD_EMAIL_STATUS,
        // MCP Tool Management Channels
        MCP_TOOL_LIST,MCP_TOOL_ADD,MCP_TOOL_UPDATE,MCP_TOOL_DELETE,MCP_TOOL_DISCOVER,MCP_TOOL_TOGGLE_SERVER,MCP_TOOL_TOGGLE_TOOL,MCP_TOOL_TEST_CONNECTION]
      if (validChannels.includes(channel)) {
        return ipcRenderer.invoke(channel, data)
      }
    }
  })